[package]
name = "wmacro-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wmacro-core-types.workspace = true
eframe.workspace = true
egui.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
log.workspace = true
env_logger.workspace = true
rfd.workspace = true
directories.workspace = true
egui-phosphor.workspace = true
image.workspace = true
imageproc.workspace = true
anyhow.workspace = true
rayon.workspace = true
rustfft.workspace = true
transpose.workspace = true
once_cell.workspace = true
which.workspace = true
pipewire.workspace = true
libspa.workspace = true
ashpd.workspace = true
tokio.workspace = true
gbm.workspace = true
gbm-sys.workspace = true
libc.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wl-clipboard-rs.workspace = true
x11rb.workspace = true
