[package]
name = "wmacro-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wmacro-core-types.workspace = true
serde.workspace = true
serde_json.workspace = true
inotify.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
evdev.workspace = true
libc.workspace = true
